# Analyse Exploratoire des Données Macroéconomiques du Maroc

Ce notebook explore l’évolution des principaux indicateurs économiques du Maroc afin d’identifier les effets potentiels de la libéralisation progressive du régime de change introduite en 2018.

In [ ]:
pip install pandas openpyxl

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>Importation des bibliotheques</T1>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>Chargement & Structure Initiale des donnees</T1>

In [20]:
# répertoire des données brutes :
data_dir = Path("..") / "data" / "processed"
csv_files = sorted([p for p in data_dir.iterdir()])

# liste de DataFrame et dict {stem: df} :
dfs = [pd.read_csv(p) for p in csv_files]
dfs_names = [p.stem for p in csv_files]
dfs_dict = dict(zip(dfs_names, dfs))

In [21]:
# Afficher un aperçu de chaque DataFrame
for name, df in dfs_dict.items():
    print(f"--- {name} ---")
    display(df.head())

--- ice_global_maroc ---

   year  value_exports  value_imports  country
0  2024   6.745425e+10   8.060860e+10  Morocco
1  2023   6.194501e+10   7.404071e+10  Morocco
2  2022   5.868192e+10   7.375289e+10  Morocco
3  2021   4.706055e+10   6.019936e+10  Morocco
4  2020   3.736977e+10   4.617469e+10  Morocco

--- ide_global_maroc ---

   Year       IDE_USD  IDE_percent_GDP  country  FDI_growth_rate
0  2024  1.639000e+09         1.020478  Morocco              NaN
1  2023  1.060024e+09         0.725864  Morocco       -35.324966
2  2022  2.294356e+09         1.748143  Morocco       116.443864
3  2021  2.264149e+09         1.594223  Morocco        -1.316597
4  2020  1.418713e+09         1.169073  Morocco       -37.340106

--- ide_par_secteur_maroc ---

            Secteur  Year  IDE_value
0         Industrie  2007     3314.4
1        Immobilier  2007     7590.8
2          Commerce  2007      343.7
3  Energie et mines  2007     2818.5
4          Tourisme  2007    12421.7

--- ipc_data_pivot ---

,annee,mois,01 - Produits alimentaires et boissons non alcoolisées,02 - Boissons alcoolisées et tabac,03 - Articles d'habillements et chaussures,"04 - Logements, eau, électricité et autres combustibles","05 - Meubles, articles de ménages et entretien courant du foyer",06 - Santé,07 - Transport,08 - Communication,09 - Loisirs et culture,10 - Enseignement,11 - Restaurants et hôtels,12 - Biens et services divers,Ensemble,Produits alimentaires,Produits non alimentaires
0,2010,août,113.9,108.3,103.7,104.4,106.2,102.9,103.2,90.5,96.8,113.3,109.7,107.1,108.0,113.6,104.1
1,2010,avril,115.6,108.3,104.2,104.2,106.0,102.9,103.3,90.6,97.4,113.3,109.1,106.5,108.7,115.2,104.0
2,2010,décembre,114.5,108.3,105.1,104.6,106.3,103.0,102.9,89.2,96.6,118.5,109.8,108.3,108.6,114.2,104.6
3,2010,février,112.5,108.3,104.5,104.2,106.0,102.5,103.5,90.9,97.8,113.3,108.2,106.4,107.5,112.3,104.1
4,2010,janvier,110.2,108.2,104.5,104.2,106.0,102.4,103.2,90.9,97.7,113.3,108.0,106.2,106.5,110.1,104.0

--- macro_control ---

   year       gdp_usd  gdp_growth  gdp_per_capita  current_account  country
0  2024  1.606110e+11    3.793365     4153.194336        -1.163541  Morocco
1  2023  1.460361e+11    3.655644     3813.726074        -1.047678  Morocco
2  2022  1.312453e+11    1.812692     3463.137695        -3.657491  Morocco
3  2021  1.420221e+11    8.154739     3785.936279        -2.357868  Morocco
4  2020  1.213536e+11   -7.178207     3268.030273        -1.127599  Morocco

--- masi ---

         Date    Dernier       Ouv.  Plus Haut   Plus Bas Vol. Variation %
0  01/02/2026  18.701,04  18.666,95  18.829,45  17.924,37  NaN       0,18%
1  01/01/2026  18.666,95  18.846,35  19.638,15  18.360,24  NaN      -0,95%
2  01/12/2025  18.846,35  18.603,59  19.144,14  18.318,91  NaN       1,30%
3  01/11/2025  18.603,59  19.636,52  20.060,07  18.106,62  NaN      -5,26%
4  01/10/2025  19.636,52  19.024,82  19.728,29  17.765,29  NaN       3,22%

--- reserves_de_change ---

   year     value_usd  value_months  country
0  2024  3.713391e+10      5.271238  Morocco
1  2023  3.632770e+10      5.634765  Morocco
2  2022  3.231425e+10      5.062121  Morocco
3  2021  3.564827e+10      6.771292  Morocco
4  2020  3.599764e+10      8.935414  Morocco

--- taux_change_maroc ---

         Date  Dernier     Ouv.  Plus Haut Plus Bas Vol. Variation %   Devise
0  30/01/2026  10,8109  10,8274    10,8495  10,7941  NaN      -0,15%  EUR/MAD
1  29/01/2026  10,8274  10,8220    10,8568  10,8024  NaN       0,04%  EUR/MAD
2  28/01/2026  10,8226  10,9024    10,9072  10,7934  NaN      -0,74%  EUR/MAD
3  27/01/2026  10,9029  10,7898    10,9368  10,7688  NaN       1,09%  EUR/MAD
4  26/01/2026  10,7857  10,7734    10,8331  10,7678  NaN       0,11%  EUR/MAD

In [22]:
# Taille des DataFrames
for name, df in dfs_dict.items():
    print(f" - {name}: {df.shape}")

 - ice_global_maroc: (15, 4)
 - ide_global_maroc: (15, 5)
 - ide_par_secteur_maroc: (304, 3)
 - ipc_data_pivot: (192, 17)
 - macro_control: (15, 6)
 - masi: (194, 7)
 - reserves_de_change: (15, 4)
 - taux_change_maroc: (8392, 8)

In [23]:
# type des colonnes des DataFrames
for name, df in dfs_dict.items():
    print(f"Types des colonnes de {name}:\n{'*'*50}\n{df.dtypes}\n")

Types des colonnes de ice_global_maroc:
**************************************************
year               int64
value_exports    float64
value_imports    float64
country           object
dtype: object

Types des colonnes de ide_global_maroc:
**************************************************
Year                 int64
IDE_USD            float64
IDE_percent_GDP    float64
country             object
FDI_growth_rate    float64
dtype: object

Types des colonnes de ide_par_secteur_maroc:
**************************************************
Secteur       object
Year          object
IDE_value    float64
dtype: object

Types des colonnes de ipc_data_pivot:
**************************************************
annee                                                                int64
mois                                                                object
01 - Produits alimentaires et boissons non alcoolisées             float64
02 - Boissons alcoolisées et tabac                                 float64
03 - Articles d'habillements et chaussures                         float64
04 - Logements, eau, électricité et autres combustibles            float64
05 - Meubles, articles de ménages et entretien courant du foyer    float64
06 - Santé                                                         float64
07 - Transport                                                     float64
08 - Communication                                                 float64
09 - Loisirs et culture                                            float64
10 - Enseignement                                                  float64
11 - Restaurants et hôtels                                         float64
12 - Biens et services divers                                      float64
Ensemble                                                           float64
Produits alimentaires                                              float64
Produits non alimentaires                                          float64
dtype: object

Types des colonnes de macro_control:
**************************************************
year                 int64
gdp_usd            float64
gdp_growth         float64
gdp_per_capita     float64
current_account    float64
country             object
dtype: object

Types des colonnes de masi:
**************************************************
Date           object
Dernier        object
Ouv.           object
 Plus Haut     object
Plus Bas       object
Vol.           object
Variation %    object
dtype: object

Types des colonnes de reserves_de_change:
**************************************************
year              int64
value_usd       float64
value_months    float64
country          object
dtype: object

Types des colonnes de taux_change_maroc:
**************************************************
Date           object
Dernier        object
Ouv.           object
 Plus Haut     object
Plus Bas       object
Vol.           object
Variation %    object
Devise         object
dtype: object

#### 🚩 **Remarque:**
- Les colonnes Date dans `taux_change_maroc` et `masi` sont de type object, il faut les convertir en datetime

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1> Analyse de Qualité des Données</T1>

In [30]:
# valeurs manquantes par colonne de chaque DataFrame
for name, df in dfs_dict.items():
    valeurs_nulles = df.isnull().sum()
    taux_valeurs_nulles = round((df.isnull().sum() / len(df)) * 100, 2)

    df_nulles = pd.DataFrame({
        'Colonne': valeurs_nulles.index,
        'Nb_Manquants': valeurs_nulles.values,
        'Pourcentage': taux_valeurs_nulles.values
    }).sort_values('Nb_Manquants', ascending=False)
    
    print(f"--- Valeurs manquantes dans {name} ---")
    print('='*50,'\n',df_nulles,'\n')

--- Valeurs manquantes dans ice_global_maroc ---
==================================================
          Colonne  Nb_Manquants  Pourcentage
0           year             0          0.0
1  value_exports             0          0.0
2  value_imports             0          0.0
3        country             0          0.0

--- Valeurs manquantes dans ide_global_maroc ---
==================================================
            Colonne  Nb_Manquants  Pourcentage
4  FDI_growth_rate             1         6.67
0             Year             0         0.00
1          IDE_USD             0         0.00
2  IDE_percent_GDP             0         0.00
3          country             0         0.00

--- Valeurs manquantes dans ide_par_secteur_maroc ---
==================================================
      Colonne  Nb_Manquants  Pourcentage
0    Secteur             0          0.0
1       Year             0          0.0
2  IDE_value             0          0.0

--- Valeurs manquantes dans ipc_data_pivot ---
==================================================
                                               Colonne  Nb_Manquants  \
0                                               annee             0
9                                  08 - Communication             0
15                              Produits alimentaires             0
14                                           Ensemble             0
13                      12 - Biens et services divers             0
12                         11 - Restaurants et hôtels             0
11                                  10 - Enseignement             0
10                            09 - Loisirs et culture             0
8                                      07 - Transport             0
1                                                mois             0
7                                          06 - Santé             0
6   05 - Meubles, articles de ménages et entretien...             0
5   04 - Logements, eau, électricité et autres com...             0
4          03 - Articles d'habillements et chaussures             0
3                  02 - Boissons alcoolisées et tabac             0
2   01 - Produits alimentaires et boissons non alc...             0
16                          Produits non alimentaires             0

    Pourcentage
0           0.0
9           0.0
15          0.0
14          0.0
13          0.0
12          0.0
11          0.0
10          0.0
8           0.0
1           0.0
7           0.0
6           0.0
5           0.0
4           0.0
3           0.0
2           0.0
16          0.0

--- Valeurs manquantes dans macro_control ---
==================================================
            Colonne  Nb_Manquants  Pourcentage
0             year             0          0.0
1          gdp_usd             0          0.0
2       gdp_growth             0          0.0
3   gdp_per_capita             0          0.0
4  current_account             0          0.0
5          country             0          0.0

--- Valeurs manquantes dans masi ---
==================================================
        Colonne  Nb_Manquants  Pourcentage
5         Vol.           193        99.48
0         Date             0         0.00
1      Dernier             0         0.00
2         Ouv.             0         0.00
3    Plus Haut             0         0.00
4     Plus Bas             0         0.00
6  Variation %             0         0.00

--- Valeurs manquantes dans reserves_de_change ---
==================================================
         Colonne  Nb_Manquants  Pourcentage
0          year             0          0.0
1     value_usd             0          0.0
2  value_months             0          0.0
3       country             0          0.0

--- Valeurs manquantes dans taux_change_maroc ---
==================================================
        Colonne  Nb_Manquants  Pourcentage
5         Vol.          6284        74.88
0         Date             0         0.00
1      Dernier             0         0.00
2         Ouv.             0         0.00
3    Plus Haut             0         0.00
4     Plus Bas             0         0.00
6  Variation %             0         0.00
7       Devise             0         0.00

In [31]:
# valeurs doublons dans chaque DataFrame
for name, df in dfs_dict.items():
    nb_doublons = df.duplicated().sum()
    print(f"Nombre de lignes dupliquées dans {name}: {nb_doublons}")

Nombre de lignes dupliquées dans ice_global_maroc: 0
Nombre de lignes dupliquées dans ide_global_maroc: 0
Nombre de lignes dupliquées dans ide_par_secteur_maroc: 0
Nombre de lignes dupliquées dans ipc_data_pivot: 0
Nombre de lignes dupliquées dans macro_control: 0
Nombre de lignes dupliquées dans masi: 0
Nombre de lignes dupliquées dans reserves_de_change: 0
Nombre de lignes dupliquées dans taux_change_maroc: 0

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1> Statistiques Descriptives</T1>

In [ ]:
# Statistiques descriptives
for name, df in dfs_dict.items():
    print(f"Descriptive statistics for {name}:")
    display(np.round(df.describe(), 2))

Descriptive statistics for ice_global_maroc:

          year  value_exports  value_imports
count    15.00   1.500000e+01   1.500000e+01
mean   2017.00   4.240424e+10   5.457641e+10
std       4.47   1.151855e+10   1.233395e+10
min    2010.00   3.004672e+10   4.009703e+10
25%    2013.50   3.466936e+10   4.772417e+10
50%    2017.00   3.736977e+10   4.974973e+10
75%    2020.50   4.550671e+10   5.774955e+10
max    2024.00   6.745425e+10   8.060860e+10

Descriptive statistics for ide_global_maroc:

          Year       IDE_USD  IDE_percent_GDP  FDI_growth_rate
count    15.00  1.500000e+01            15.00            14.00
mean   2017.00  2.367872e+09             1.97             7.35
std       4.47  8.338126e+08             0.77            50.96
min    2010.00  1.060024e+09             0.73           -50.80
25%    2013.50  1.679912e+09             1.28           -23.20
50%    2017.00  2.294356e+09             1.93            -7.97
75%    2020.50  3.047434e+09             2.72            18.07
max    2024.00  3.544387e+09             2.96           116.44

Descriptive statistics for ide_par_secteur_maroc:

       IDE_value
count     304.00
mean     4448.86
std      8756.08
min         0.80
25%       342.22
50%      1406.70
75%      3254.85
max     46099.00

Descriptive statistics for ipc_data_pivot:

,annee,01 - Produits alimentaires et boissons non alcoolisées,02 - Boissons alcoolisées et tabac,03 - Articles d'habillements et chaussures,"04 - Logements, eau, électricité et autres combustibles","05 - Meubles, articles de ménages et entretien courant du foyer",06 - Santé,07 - Transport,08 - Communication,09 - Loisirs et culture,10 - Enseignement,11 - Restaurants et hôtels,12 - Biens et services divers,Ensemble,Produits alimentaires,Produits non alimentaires
count,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00,192.00
mean,2017.50,120.95,126.81,111.63,108.69,108.50,103.56,110.84,79.79,99.92,129.03,118.10,113.25,113.96,121.13,108.94
std,4.62,8.63,14.73,4.89,5.11,3.28,1.75,6.01,20.32,3.38,14.72,9.28,5.24,5.46,8.58,3.65
min,2010.00,99.20,108.20,102.10,101.50,100.70,100.90,95.90,58.30,96.20,108.40,103.20,103.80,101.60,100.00,101.60
25%,2013.75,117.10,116.12,107.68,104.57,107.18,101.80,107.38,59.50,96.90,116.70,110.38,110.10,109.98,116.70,105.30
50%,2017.50,122.55,122.80,112.50,107.05,108.60,103.55,110.40,71.65,98.90,122.10,117.70,113.25,114.80,122.40,109.60
75%,2021.25,127.50,138.50,116.10,113.80,111.32,104.90,113.50,103.90,101.60,141.40,124.25,115.30,118.70,127.82,111.93
max,2025.00,132.40,159.40,119.10,117.70,113.20,107.90,126.20,104.30,106.20,157.60,134.80,124.60,121.30,132.80,115.60

Descriptive statistics for macro_control:

          year       gdp_usd  gdp_growth  gdp_per_capita  current_account
count    15.00  1.500000e+01       15.00           15.00            15.00
mean   2017.00  1.233874e+11        3.00         3428.45            -3.92
std       4.47  1.630261e+10        3.30          297.38             2.38
min    2010.00  1.008653e+11       -7.18         3067.99            -8.95
25%    2013.50  1.109934e+11        2.81         3216.10            -5.21
50%    2017.00  1.191308e+11        3.50         3379.74            -3.66
75%    2020.50  1.300828e+11        4.23         3504.90            -2.16
max    2024.00  1.606110e+11        8.15         4153.19            -1.05

Descriptive statistics for masi:

,Date,Dernier,Ouv.,Plus Haut,Plus Bas,Vol.,Variation %
count,194,194,194,194,194,1,194
unique,194,193,194,194,194,1,181
top,01/02/2026,"12.196,70","18.666,95","18.829,45","17.924,37","0,02K","-0,07%"
freq,1,2,1,1,1,1,3

Descriptive statistics for reserves_de_change:

          year     value_usd  value_months
count    15.00  1.500000e+01         15.00
mean   2017.00  2.682773e+10          5.76
std       4.47  6.916311e+09          1.24
min    2010.00  1.713821e+10          4.12
25%    2013.50  2.151081e+10          5.00
50%    2017.00  2.509626e+10          5.58
75%    2020.50  3.398126e+10          6.30
max    2024.00  3.713391e+10          8.94

Descriptive statistics for taux_change_maroc:

,Date,Dernier,Ouv.,Plus Haut,Plus Bas,Vol.,Variation %,Devise
count,8392,8392,8392,8392,8392,2108,8392,8392
unique,4196,6994,6973,7095,6980,2037,276,2
top,30/01/2026,"11,2307","9,6805","11,1828","11,0253","68,51K","-0,02%",EUR/MAD
freq,2,5,5,5,5,3,156,4196

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1> Analyse des Incohérences</T1>

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1> Analyse de la distribution</T1>