<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>Importation des bibliotheuqes</T1>

In [14]:
import pandas as pd
import glob
import os
import json
import re

In [15]:
# definir le chemin vers les données
data_path = "../data/interim/maroc/"
processed_path = "../data/processed/"

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>1- Taux de change</T1>

🚩 les deux ont meme noms de colonnes et meme forme de dates.

In [18]:
# Chargement des fichiers brutes pour Taux de change 
usd_mad = pd.read_csv(data_path + "taux de change/USD_MAD - Données Historiques.csv")
eur_mad = pd.read_csv(data_path + "taux de change/EUR_MAD - Données Historiques.csv")

print('Avant :')
display(usd_mad.head())
display(eur_mad.head())

# concater les deux dataframes
eur_mad["Devise"] = "EUR/MAD"
usd_mad["Devise"] = "USD/MAD"

df_concat = pd.concat([eur_mad, usd_mad], ignore_index=True)

# sauvegarder fichier final
df_concat.to_csv(processed_path + "taux_change_maroc.csv", index=False)

print('Apres :')
display(df_concat.head())

# verification
lignes_totales = len(eur_mad) + len(usd_mad)
lignes_concat = len(df_concat)

print('Verification :')
print(f"Lignes dans EUR_MAD : {len(eur_mad)}")
print(f"Lignes dans USD_MAD : {len(usd_mad)}")  
print(f"Lignes totales attendues : {lignes_totales}")
print(f"Lignes dans le dataframe concaténé : {lignes_concat}")

Avant :

         Date Dernier    Ouv.  Plus Haut Plus Bas Vol. Variation %
0  30/01/2026  9,1231  9,0437     9,1255   9,0376  NaN       0,86%
1  29/01/2026  9,0451  9,0530     9,0860   9,0297  NaN      -0,09%
2  28/01/2026  9,0535  9,0543     9,0837   9,0157  NaN      -0,01%
3  27/01/2026  9,0544  9,0820     9,0987   9,0320  NaN      -0,30%
4  26/01/2026  9,0819  9,1171     9,1271   9,0655  NaN      -0,28%

         Date  Dernier     Ouv.  Plus Haut Plus Bas Vol. Variation %
0  30/01/2026  10,8109  10,8274    10,8495  10,7941  NaN      -0,15%
1  29/01/2026  10,8274  10,8220    10,8568  10,8024  NaN       0,04%
2  28/01/2026  10,8226  10,9024    10,9072  10,7934  NaN      -0,74%
3  27/01/2026  10,9029  10,7898    10,9368  10,7688  NaN       1,09%
4  26/01/2026  10,7857  10,7734    10,8331  10,7678  NaN       0,11%

Apres :

         Date  Dernier     Ouv.  Plus Haut Plus Bas Vol. Variation %   Devise
0  30/01/2026  10,8109  10,8274    10,8495  10,7941  NaN      -0,15%  EUR/MAD
1  29/01/2026  10,8274  10,8220    10,8568  10,8024  NaN       0,04%  EUR/MAD
2  28/01/2026  10,8226  10,9024    10,9072  10,7934  NaN      -0,74%  EUR/MAD
3  27/01/2026  10,9029  10,7898    10,9368  10,7688  NaN       1,09%  EUR/MAD
4  26/01/2026  10,7857  10,7734    10,8331  10,7678  NaN       0,11%  EUR/MAD

Verification :
Lignes dans EUR_MAD : 4196
Lignes dans USD_MAD : 4196
Lignes totales attendues : 8392
Lignes dans le dataframe concaténé : 8392

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>2- Investissements directs étrangers (IDE)</T1>

<style>
T1 {
    display: inline-block;
    background: #fef2eb;
    color: #fc8530e1;
    padding: 10px 16px;
    border-radius: 8px; 
    font-size: 18px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>a- Pour le fichier IDE global</T1>

In [20]:
# Charger le fichier IDE global
ide_global = pd.read_csv(data_path + "IDE/ide_global_data_2010_2025.csv")

# Renommer les colonnes pour uniformité
ide_global = ide_global.rename(columns={
    "year": "Year",
    "value_usd": "IDE_USD",
    "value_percent_gdp": "IDE_percent_GDP",
    "fdi_growth_rate": "FDI_growth_rate"
})

# Vérifier le résultat
display(ide_global.head())

# Sauvegarder le fichier final
ide_global.to_csv(processed_path + "ide_global_maroc.csv", index=False)

   Year       IDE_USD  IDE_percent_GDP  country  FDI_growth_rate
0  2024  1.639000e+09         1.020478  Morocco              NaN
1  2023  1.060024e+09         0.725864  Morocco       -35.324966
2  2022  2.294356e+09         1.748143  Morocco       116.443864
3  2021  2.264149e+09         1.594223  Morocco        -1.316597
4  2020  1.418713e+09         1.169073  Morocco       -37.340106

<style>
T1 {
    display: inline-block;
    background: #fef2eb;
    color: #fc8530e1;
    padding: 10px 16px;
    border-radius: 8px; 
    font-size: 18px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>b- Pour le fichier IDE par secteur</T1>

In [ ]:
# Charger le fichier IDE par secteurs
ide_sector = pd.read_excel(data_path + "IDE/Investissements directs étrangers au Maroc_Recettes par secteurs_14.xlsx")

print('Avant :')
display(ide_sector.head())

# Transformer le fichier de wide format en long format
ide_sector_long = ide_sector.melt(
    id_vars="SECTEURS D'ACTIVITE",
    var_name="Year",
    value_name="IDE_value"
)

# Renommer la colonne des secteurs
ide_sector_long = ide_sector_long.rename(columns={
    "SECTEURS D'ACTIVITE": "Secteur"
})

# Vérifier le résultat
print('Apres transformation 1 :')
display(ide_sector_long.head(16))


# Pivot de la table pour avoir les secteurs en colonnes et les années en lignes

ide_sector_pivot = ide_sector_long.pivot_table(
    index="Year",
    columns="Secteur",
    values="IDE_value",
    aggfunc="first"
).reset_index()

# Supprimer le nom de l'axe colonnes (artefact de pivot_table)
ide_sector_pivot.columns.name = None

# Vérifier le résultat
print('Apres transformation 2 :')
display(ide_sector_pivot.head())

# Sauvegarder le fichier pivoté
ide_sector_pivot.to_csv(processed_path + "ide_par_secteur_maroc.csv", index=False)

Avant :

,SECTEURS D'ACTIVITE,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024*,Janv-Sept 2025*
0,Industrie,3314.4,1784.0,2724.9,4772.1,6129.5,8169.0,15335.0,9893.0,8714.2,9676.0,6816.8,8743.4,12670,7905,9207,15224,14265,16464,15988
1,Immobilier,7590.8,9152.0,5554.6,7268.4,8118.5,7331.5,7572.6,10790.5,10799.0,11210.9,9866.7,7148.9,7078,5770,6578,7483,7484,9644,9118
2,Commerce,343.7,179.7,180.2,1240.0,1755.9,1479.7,2282.0,2609.1,2565.8,4654.1,3119.5,4047.3,1825,2492,2694,1748,3415,2872,3687
3,Energie et mines,2818.5,1568.4,155.0,754.0,1799.2,5591.8,2250.6,1419.4,2081.3,499.3,2118.5,3886.3,1337,1825,1273,1662,3204,2361,3658
4,Tourisme,12421.7,5674.9,2872.7,4058.9,2564.8,1680.0,3340.6,3389.5,2349.8,1080.7,736.6,2338.6,2377,997,2581,2237,2359,1843,2616

Apres transformation 1 :

               Secteur  Year  IDE_value
0            Industrie  2007     3314.4
1           Immobilier  2007     7590.8
2             Commerce  2007      343.7
3     Energie et mines  2007     2818.5
4             Tourisme  2007    12421.7
5              Holding  2007      847.8
6               Banque  2007     1823.7
7            Assurance  2007       21.4
8          Agriculture  2007       33.0
9           Transports  2007     2737.5
10      Grands travaux  2007      532.1
11  Télécommunications  2007     3086.9
12               Pêche  2007        3.7
13     Autres services  2007     2255.9
14     Divers secteurs  2007      127.9
15               TOTAL  2007    37959.0

Apres transformation 2 :

,Year,Agriculture,Assurance,Autres services,Banque,Commerce,Divers secteurs,Energie et mines,Grands travaux,Holding,Immobilier,Industrie,Pêche,TOTAL,Tourisme,Transports,Télécommunications
0,2007,33.0,21.4,2255.9,1823.7,343.7,127.9,2818.5,532.1,847.8,7590.8,3314.4,3.7,37959.0,12421.7,2737.5,3086.9
1,2008,27.0,200.7,1493.6,4959.6,179.7,34.0,1568.4,252.3,2209.2,9152.0,1784.0,21.6,27963.0,5674.9,175.9,230.1
2,2009,25.6,451.6,795.9,6444.8,180.2,40.4,155.0,112.1,171.2,5554.6,2724.9,0.8,25249.7,2872.7,379.2,5340.7
3,2010,60.6,206.6,1337.6,4562.7,1240.0,53.2,754.0,424.1,961.2,7268.4,4772.1,21.2,35068.3,4058.9,593.5,8754.2
4,2011,92.4,148.6,1440.2,1357.4,1755.9,167.5,1799.2,570.7,1172.6,8118.5,6129.5,20.0,26060.2,2564.8,302.1,420.8

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>3- Indice des prix a la consommation (IPC) </T1>

In [16]:
"""
PRÉPARATION DES DONNÉES IPC (INFLATION)
=======================================
1. Concaténation de tous les fichiers IPC
2. Normalisation des noms de catégories
3. Pivotage pour structure finale
"""

print("PRÉPARATION DES DONNÉES IPC - INFLATION")
print("="*80)


#-------------------------Configuration
IPC_FOLDER = "../data/interim/maroc/inflation"
OUTPUT_FOLDER = "../data/interim/maroc/inflation_prepared"
OUTPUT_FOLDER2 = "../data/processed"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

#-------------------------Étape 1 : concatenation des fichiers IPC
def concatenate_ipc_files(folder_path):
    """
    Concatène tous les fichiers CSV d'IPC en un seul DataFrame
    """
    
    print(f"\n{'='*80}")
    print("ÉTAPE 1 : CONCATÉNATION DES FICHIERS")
    print(f"{'='*80}\n")
    
    # Trouver tous les fichiers CSV dans le dossier
    csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
    
    if len(csv_files) == 0:
        print(f"Aucun fichier CSV trouvé dans {folder_path}")
        return None
    
    print(f"Fichiers trouvés : {len(csv_files)}\n")
    
    # Liste pour stocker tous les DataFrames
    all_dataframes = []
    
    for i, file in enumerate(csv_files, 1):
        try:
            # Lire le fichier
            df = pd.read_csv(file, encoding='utf-8-sig')
            
            # Vérifier que les colonnes attendues sont présentes
            required_cols = ['Division par produits', 'ipc', 'annee', 'mois']
            
            # Gérer les variations de noms de colonnes
            df.columns = df.columns.str.strip()
            
            # Renommer si nécessaire (gestion des variations)
            column_mapping = {
                'Division par produit': 'Division par produits',
                'Divison par produits': 'Division par produits',
                'année': 'annee',
                'Année': 'annee',
                'IPC': 'ipc'
            }
            df.rename(columns=column_mapping, inplace=True)
            
            # Vérifier à nouveau
            missing_cols = set(required_cols) - set(df.columns)
            if missing_cols:
                print(f"Fichier {os.path.basename(file)} : colonnes manquantes {missing_cols}")
                continue
            
            # Sélectionner uniquement les colonnes nécessaires
            df = df[required_cols]
            
            all_dataframes.append(df)
            print(f"{i:3d}. {os.path.basename(file):40s} : {len(df):4d} lignes")
            
        except Exception as e:
            print(f"{i:3d}. {os.path.basename(file):40s} : Erreur - {e}")
    
    # Concaténer tous les DataFrames
    if all_dataframes:
        df_combined = pd.concat(all_dataframes, ignore_index=True)
        print(f"\nTotal combiné : {len(df_combined):,} lignes × {len(df_combined.columns)} colonnes")
        return df_combined
    else:
        print("Aucun fichier valide n'a pu être chargé")
        return None

#-------------------------Étape 2 : normalisation des catégories

def normalize_category_names(df):
    """
    Uniformiser les noms de catégories en utilisant les codes
    """
    
    print(f"\n{'='*80}")
    print("ÉTAPE 2 : NORMALISATION DES CATÉGORIES")
    print(f"{'='*80}\n")
    
    # Dictionnaire de mapping : code → nom standardisé
    CATEGORY_MAPPING = {
        '01': '01 - Produits alimentaires et boissons non alcoolisées',
        '02': '02 - Boissons alcoolisées et tabac',
        '03': '03 - Articles d\'habillements et chaussures',
        '04': '04 - Logements, eau, électricité et autres combustibles',
        '05': '05 - Meubles, articles de ménages et entretien courant du foyer',
        '06': '06 - Santé',
        '07': '07 - Transport',
        '08': '08 - Communication',
        '09': '09 - Loisirs et culture',
        '10': '10 - Enseignement',
        '11': '11 - Restaurants et hôtels',
        '12': '12 - Biens et services divers',
        'Ensemble': 'Ensemble',
        'Produits alimentaires': 'Produits alimentaires',
        'Produits non alimentaires': 'Produits non alimentaires'
    }
    
    print("Catégories uniques avant normalisation :")
    unique_categories_before = df['Division par produits'].unique()
    print(f"   Nombre : {len(unique_categories_before)}")
    for cat in sorted(unique_categories_before):
        count = (df['Division par produits'] == cat).sum()
        print(f"   - {cat:60s} : {count:6,} lignes")
    
    # Fonction pour normaliser une catégorie
    def normalize_category(category):
        """
        Normalise le nom d'une catégorie en détectant son code
        """
        category = str(category).strip()
        
        # Extraire le code (2 premiers chiffres)
        if len(category) >= 2 and category[:2].isdigit():
            code = category[:2]
            if code in CATEGORY_MAPPING:
                return CATEGORY_MAPPING[code]
        
        # Cas spéciaux (Ensemble, Produits alimentaires, etc.)
        for key, value in CATEGORY_MAPPING.items():
            if not key.isdigit():  # Seulement pour les cas spéciaux
                # Comparaison flexible
                if key.lower() in category.lower():
                    return value
        
        # Si aucune correspondance, retourner l'original
        return category
    
    # Appliquer la normalisation
    df['Division par produits'] = df['Division par produits'].apply(normalize_category)
    
    print(f"\nCatégories uniques après normalisation :")
    unique_categories_after = df['Division par produits'].unique()
    print(f"   Nombre : {len(unique_categories_after)}")
    for cat in sorted(unique_categories_after):
        count = (df['Division par produits'] == cat).sum()
        print(f"   - {cat:60s} : {count:6,} lignes")
    
    print(f"\nNormalisation terminée : {len(unique_categories_before)} → {len(unique_categories_after)} catégories")
    
    return df

# -------------------------Étape 3 : nettoyage des données
def clean_data(df):
    """
    Nettoyer les données avant pivotage
    """
    
    print(f"\n{'='*80}")
    print("ÉTAPE 3 : NETTOYAGE DES DONNÉES")
    print(f"{'='*80}\n")
    
    # Nombre de lignes avant nettoyage
    n_before = len(df)
    
    # 1. Supprimer les doublons
    df = df.drop_duplicates(subset=['annee', 'mois', 'Division par produits'])
    n_duplicates = n_before - len(df)
    print(f"Doublons supprimés : {n_duplicates:,}")
    
    # 2. Supprimer les valeurs manquantes
    df = df.dropna(subset=['ipc'])
    n_missing = n_before - n_duplicates - len(df)
    print(f"Valeurs manquantes supprimées : {n_missing:,}")
    
    # 3. Convertir IPC en numérique
    df['ipc'] = pd.to_numeric(df['ipc'], errors='coerce')
    
    # 4. Vérifier les valeurs aberrantes
    ipc_min = df['ipc'].min()
    ipc_max = df['ipc'].max()
    print(f"\nPlage IPC : {ipc_min:.2f} → {ipc_max:.2f}")
    
    if ipc_min < 50 or ipc_max > 200:
        print(f"Attention : valeurs IPC inhabituelles détectées")
    
    # 5. Standardiser les noms de mois
    mois_mapping = {
        'janvier': 'janvier', 'jan': 'janvier',
        'février': 'février', 'fév': 'février', 'fevrier': 'février',
        'mars': 'mars', 'mar': 'mars',
        'avril': 'avril', 'avr': 'avril',
        'mai': 'mai',
        'juin': 'juin',
        'juillet': 'juillet', 'juil': 'juillet',
        'août': 'août', 'aout': 'août',
        'septembre': 'septembre', 'sep': 'septembre', 'sept': 'septembre',
        'octobre': 'octobre', 'oct': 'octobre',
        'novembre': 'novembre', 'nov': 'novembre',
        'décembre': 'décembre', 'déc': 'décembre', 'dec': 'décembre', 'decembre': 'décembre'
    }
    
    df['mois'] = df['mois'].str.lower().str.strip().map(mois_mapping)
    
    # 6. Vérifier les années
    annee_min = df['annee'].min()
    annee_max = df['annee'].max()
    print(f"Période : {annee_min} → {annee_max}")
    
    print(f"\nNettoyage terminé : {len(df):,} lignes restantes")
    
    return df

# -------------------------Étape 4 : pivotage des données

def pivot_data(df):
    """
    Pivoter le DataFrame pour avoir la structure finale
    Index : (annee, mois)
    Colonnes : Division par produits
    Valeurs : ipc
    """
    
    print(f"\n{'='*80}")
    print("ÉTAPE 4 : PIVOTAGE DES DONNÉES")
    print(f"{'='*80}\n")
    
    # Créer une colonne de date pour faciliter le tri
    mois_to_num = {
        'janvier': 1, 'février': 2, 'mars': 3, 'avril': 4,
        'mai': 5, 'juin': 6, 'juillet': 7, 'août': 8,
        'septembre': 9, 'octobre': 10, 'novembre': 11, 'décembre': 12
    }
    
    df['mois_num'] = df['mois'].map(mois_to_num)
    
    # Trier par année et mois
    df = df.sort_values(['annee', 'mois_num'])
    
    # Pivoter
    df_pivot = df.pivot_table(
        index=['annee', 'mois'],
        columns='Division par produits',
        values='ipc',
        aggfunc='mean'  # En cas de doublons, prendre la moyenne
    )
    
    print(f"Dimensions du tableau pivoté : {df_pivot.shape[0]} lignes × {df_pivot.shape[1]} colonnes")
    print(f"\nColonnes (catégories) :")
    for col in df_pivot.columns:
        print(f"   - {col}")
    
    # Aperçu
    print(f"\nAperçu des données pivotées :\n")
    print(df_pivot.head(10))
    
    return df_pivot

# -------------------------Étape 5 : sauvegarde

def save_data(df, df_pivot, output_folder):
    """
    Sauvegarder les données traitées
    """
    
    print(f"\n{'='*80}")
    print("ÉTAPE 5 : SAUVEGARDE")
    print(f"{'='*80}\n")
    
    # 1. DataFrame nettoyé (format long)
    output_long = os.path.join(output_folder, 'ipc_data_clean.csv')
    df.to_csv(output_long, index=False, encoding='utf-8-sig')
    print(f"Données nettoyées (format long) : {output_long}")
    
    # 2. DataFrame pivoté (format large)
    output_pivot = os.path.join(output_folder, 'ipc_data_pivot.csv')
    df_pivot.to_csv(output_pivot, encoding='utf-8-sig')
    print(f"Données pivotées (format large) : {output_pivot}")
    
    # 3. Export Excel avec les deux formats
    output_excel = os.path.join(output_folder, 'ipc_data_complet.xlsx')
    with pd.ExcelWriter(output_excel, engine='openpyxl') as writer:
        df.to_excel(writer, sheet_name='Format long', index=False)
        df_pivot.to_excel(writer, sheet_name='Format pivot')
    
    print(f"Fichier Excel complet : {output_excel}")
    
    # 4. Métadonnées
    metadata = {
        'date_traitement': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'),
        'nombre_lignes_long': len(df),
        'nombre_lignes_pivot': len(df_pivot),
        'nombre_categories': len(df['Division par produits'].unique()),
        'periode_min': f"{df['annee'].min()}-{df['mois'].value_counts().index[0]}",
        'periode_max': f"{df['annee'].max()}-{df['mois'].value_counts().index[0]}",
        'categories': df['Division par produits'].unique().tolist()
    }
    
    metadata_file = os.path.join(output_folder, 'ipc_metadata.json')
    with open(metadata_file, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)
    
    print(f"Métadonnées : {metadata_file}")

#-------------------------Fonction principale pour exécuter le pipeline complet

def prepare_ipc_data(input_folder, output_folder):
    """
    Pipeline complet de préparation des données IPC
    """
    
    # Étape 1 : Concaténation
    df = concatenate_ipc_files(input_folder)
    
    if df is None:
        print("Échec de la concaténation")
        return None, None
    
    # Étape 2 : Normalisation
    df = normalize_category_names(df)
    
    # Étape 3 : Nettoyage
    df = clean_data(df)
    
    # Étape 4 : Pivotage
    df_pivot = pivot_data(df)
    
    # Étape 5 : Sauvegarde
    save_data(df, df_pivot, output_folder)
    save_data(df, df_pivot, OUTPUT_FOLDER2)
    
    print(f"\n{'='*80}")
    print("PRÉPARATION TERMINÉE AVEC SUCCÈS")
    print(f"{'='*80}\n")
    
    return df, df_pivot

#-------------------------Execution

if __name__ == "__main__":
    
    # Exécuter le pipeline
    df_clean, df_pivot = prepare_ipc_data(IPC_FOLDER, OUTPUT_FOLDER)
    
    # Vérification finale
    if df_clean is not None and df_pivot is not None:
        print("Résumé final :")
        print(f"   Format long : {len(df_clean):,} lignes")
        print(f"   Format pivot : {df_pivot.shape[0]} lignes × {df_pivot.shape[1]} colonnes")
        print(f"   Période : {df_clean['annee'].min()} - {df_clean['annee'].max()}")

PRÉPARATION DES DONNÉES IPC - INFLATION
================================================================================

================================================================================
ÉTAPE 1 : CONCATÉNATION DES FICHIERS
================================================================================

Fichiers trouvés : 192

  1. ipc_2010_01.csv                          :   15 lignes
  2. ipc_2010_02.csv                          :   15 lignes
  3. ipc_2010_03.csv                          :   15 lignes
  4. ipc_2010_04.csv                          :   15 lignes
  5. ipc_2010_05.csv                          :   15 lignes
  6. ipc_2010_06.csv                          :   15 lignes
  7. ipc_2010_07.csv                          :   15 lignes
  8. ipc_2010_08.csv                          :   15 lignes
  9. ipc_2010_09.csv                          :   15 lignes
 10. ipc_2010_10.csv                          :   15 lignes
 11. ipc_2010_11.csv                          :   15 lignes
 12. ipc_2010_12.csv                          :   15 lignes
 13. ipc_2011_01.csv                          :   15 lignes
 14. ipc_2011_02.csv                          :   15 lignes
 15. ipc_2011_03.csv                          :   15 lignes
 16. ipc_2011_04.csv                          :   15 lignes
 17. ipc_2011_05.csv                          :   15 lignes
 18. ipc_2011_06.csv                          :   15 lignes
 19. ipc_2011_07.csv                          :   15 lignes
 20. ipc_2011_08.csv                          :   15 lignes
 21. ipc_2011_09.csv                          :   15 lignes
 22. ipc_2011_10.csv                          :   15 lignes
 23. ipc_2011_11.csv                          :   15 lignes
 24. ipc_2011_12.csv                          :   15 lignes
 25. ipc_2012_01.csv                          :   15 lignes
 26. ipc_2012_02.csv                          :   15 lignes
 27. ipc_2012_03.csv                          :   15 lignes
 28. ipc_2012_04.csv                          :   15 lignes
 29. ipc_2012_05.csv                          :   15 lignes
 30. ipc_2012_06.csv                          :   15 lignes
 31. ipc_2012_07.csv                          :   15 lignes
 32. ipc_2012_08.csv                          :   15 lignes
 33. ipc_2012_09.csv                          :   15 lignes
 34. ipc_2012_10.csv                          :   15 lignes
 35. ipc_2012_11.csv                          :   15 lignes
 36. ipc_2012_12.csv                          :   15 lignes
 37. ipc_2013_01.csv                          :   15 lignes
 38. ipc_2013_02.csv                          :   15 lignes
 39. ipc_2013_03.csv                          :   15 lignes
 40. ipc_2013_04.csv                          :   15 lignes
 41. ipc_2013_05.csv                          :   15 lignes
 42. ipc_2013_06.csv                          :   15 lignes
 43. ipc_2013_07.csv                          :   15 lignes
 44. ipc_2013_08.csv                          :   15 lignes
 45. ipc_2013_09.csv                          :   15 lignes
 46. ipc_2013_10.csv                          :   15 lignes
 47. ipc_2013_11.csv                          :   15 lignes
 48. ipc_2013_12.csv                          :   15 lignes
 49. ipc_2014_01.csv                          :   15 lignes
 50. ipc_2014_02.csv                          :   15 lignes
 51. ipc_2014_03.csv                          :   15 lignes
 52. ipc_2014_04.csv                          :   15 lignes
 53. ipc_2014_05.csv                          :   15 lignes
 54. ipc_2014_06.csv                          :   15 lignes
 55. ipc_2014_07.csv                          :   15 lignes
 56. ipc_2014_08.csv                          :   15 lignes
 57. ipc_2014_09.csv                          :   15 lignes
 58. ipc_2014_10.csv                          :   15 lignes
 59. ipc_2014_11.csv                          :   15 lignes
 60. ipc_2014_12.csv                          :   15 lignes
 61. ipc_2015_01.csv                          :   15 lignes
 62. ipc_2015_02.csv                          :   15 lignes
 63. ipc_2015_03.csv                          :   15 lignes
 64. ipc_2015_04.csv                          :   15 lignes
 65. ipc_2015_05.csv                          :   15 lignes
 66. ipc_2015_06.csv                          :   15 lignes
 67. ipc_2015_07.csv                          :   15 lignes
 68. ipc_2015_08.csv                          :   15 lignes
 69. ipc_2015_09.csv                          :   15 lignes
 70. ipc_2015_10.csv                          :   15 lignes
 71. ipc_2015_11.csv                          :   15 lignes
 72. ipc_2015_12.csv                          :   15 lignes
 73. ipc_2016_01.csv                          :   15 lignes
 74. ipc_2016_02.csv                          :   15 lignes
 75. ipc_2016_03.csv                          :   15 lignes
 76. ipc_2016_04.csv                          :   15 lignes
 77. ipc_2016_05.csv                          :   15 lignes
 78. ipc_2016_06.csv                          :   15 lignes
 79. ipc_2016_07.csv                          :   15 lignes
 80. ipc_2016_08.csv                          :   15 lignes
 81. ipc_2016_09.csv                          :   15 lignes
 82. ipc_2016_10.csv                          :   15 lignes
 83. ipc_2016_11.csv                          :   15 lignes
 84. ipc_2016_12.csv                          :   15 lignes
 85. ipc_2017_01.csv                          :   15 lignes
 86. ipc_2017_02.csv                          :   15 lignes
 87. ipc_2017_03.csv                          :   15 lignes
 88. ipc_2017_04.csv                          :   15 lignes
 89. ipc_2017_05.csv                          :   15 lignes
 90. ipc_2017_06.csv                          :   15 lignes
 91. ipc_2017_07.csv                          :   15 lignes
 92. ipc_2017_08.csv                          :   15 lignes
 93. ipc_2017_09.csv                          :   15 lignes
 94. ipc_2017_10.csv                          :   15 lignes
 95. ipc_2017_11.csv                          :   15 lignes
 96. ipc_2017_12.csv                          :   15 lignes
 97. ipc_2018_01.csv                          :   15 lignes
 98. ipc_2018_02.csv                          :   15 lignes
 99. ipc_2018_03.csv                          :   15 lignes
100. ipc_2018_04.csv                          :   15 lignes
101. ipc_2018_05.csv                          :   15 lignes
102. ipc_2018_06.csv                          :   15 lignes
103. ipc_2018_07.csv                          :   15 lignes
104. ipc_2018_08.csv                          :   15 lignes
105. ipc_2018_09.csv                          :   15 lignes
106. ipc_2018_10.csv                          :   15 lignes
107. ipc_2018_11.csv                          :   15 lignes
108. ipc_2018_12.csv                          :   15 lignes
109. ipc_2019_01.csv                          :   15 lignes
110. ipc_2019_02.csv                          :   15 lignes
111. ipc_2019_03.csv                          :   15 lignes
112. ipc_2019_04.csv                          :   15 lignes
113. ipc_2019_05.csv                          :   15 lignes
114. ipc_2019_06.csv                          :   15 lignes
115. ipc_2019_07.csv                          :   15 lignes
116. ipc_2019_08.csv                          :   15 lignes
117. ipc_2019_09.csv                          :   15 lignes
118. ipc_2019_10.csv                          :   15 lignes
119. ipc_2019_11.csv                          :   15 lignes
120. ipc_2019_12.csv                          :   15 lignes
121. ipc_2020_01.csv                          :   15 lignes
122. ipc_2020_02.csv                          :   15 lignes
123. ipc_2020_03.csv                          :   15 lignes
124. ipc_2020_04.csv                          :   15 lignes
125. ipc_2020_05.csv                          :   15 lignes
126. ipc_2020_06.csv                          :   15 lignes
127. ipc_2020_07.csv                          :   15 lignes
128. ipc_2020_08.csv                          :   15 lignes
129. ipc_2020_09.csv                          :   15 lignes
130. ipc_2020_10.csv                          :   15 lignes
131. ipc_2020_11.csv                          :   15 lignes
132. ipc_2020_12.csv                          :   15 lignes
133. ipc_2021_01.csv                          :   15 lignes
134. ipc_2021_02.csv                          :   15 lignes
135. ipc_2021_03.csv                          :   15 lignes
136. ipc_2021_04.csv                          :   15 lignes
137. ipc_2021_05.csv                          :   15 lignes
138. ipc_2021_06.csv                          :   15 lignes
139. ipc_2021_07.csv                          :   15 lignes
140. ipc_2021_08.csv                          :   15 lignes
141. ipc_2021_09.csv                          :   15 lignes
142. ipc_2021_10.csv                          :   15 lignes
143. ipc_2021_11.csv                          :   15 lignes
144. ipc_2021_12.csv                          :   15 lignes
145. ipc_2022_01.csv                          :   15 lignes
146. ipc_2022_02.csv                          :   15 lignes
147. ipc_2022_03.csv                          :   15 lignes
148. ipc_2022_04.csv                          :   15 lignes
149. ipc_2022_05.csv                          :   15 lignes
150. ipc_2022_06.csv                          :   15 lignes
151. ipc_2022_07.csv                          :   15 lignes
152. ipc_2022_08.csv                          :   15 lignes
153. ipc_2022_09.csv                          :   15 lignes
154. ipc_2022_10.csv                          :   15 lignes
155. ipc_2022_11.csv                          :   15 lignes
156. ipc_2022_12.csv                          :   15 lignes
157. ipc_2023_01.csv                          :   15 lignes
158. ipc_2023_02.csv                          :   15 lignes
159. ipc_2023_03.csv                          :   15 lignes
160. ipc_2023_04.csv                          :   15 lignes
161. ipc_2023_05.csv                          :   15 lignes
162. ipc_2023_06.csv                          :   15 lignes
163. ipc_2023_07.csv                          :   15 lignes
164. ipc_2023_08.csv                          :   15 lignes
165. ipc_2023_09.csv                          :   15 lignes
166. ipc_2023_10.csv                          :   15 lignes
167. ipc_2023_11.csv                          :   15 lignes
168. ipc_2023_12.csv                          :   15 lignes
169. ipc_2024_01.csv                          :   15 lignes
170. ipc_2024_02.csv                          :   15 lignes
171. ipc_2024_03.csv                          :   15 lignes
172. ipc_2024_04.csv                          :   15 lignes
173. ipc_2024_05.csv                          :   15 lignes
174. ipc_2024_06.csv                          :   15 lignes
175. ipc_2024_07.csv                          :   15 lignes
176. ipc_2024_08.csv                          :   15 lignes
177. ipc_2024_09.csv                          :   15 lignes
178. ipc_2024_10.csv                          :   15 lignes
179. ipc_2024_11.csv                          :   15 lignes
180. ipc_2024_12.csv                          :   15 lignes
181. ipc_2025_01.csv                          :   15 lignes
182. ipc_2025_02.csv                          :   15 lignes
183. ipc_2025_03.csv                          :   15 lignes
184. ipc_2025_04.csv                          :   15 lignes
185. ipc_2025_05.csv                          :   15 lignes
186. ipc_2025_06.csv                          :   15 lignes
187. ipc_2025_07.csv                          :   15 lignes
188. ipc_2025_08.csv                          :   15 lignes
189. ipc_2025_09.csv                          :   15 lignes
190. ipc_2025_10.csv                          :   15 lignes
191. ipc_2025_11.csv                          :   15 lignes
192. ipc_2025_12.csv                          :   15 lignes

Total combiné : 2,880 lignes × 4 colonnes

================================================================================
ÉTAPE 2 : NORMALISATION DES CATÉGORIES
================================================================================

Catégories uniques avant normalisation :
   Nombre : 25
   - 01 - Produits alimentaires et boissons non alcoolisées       :    192 lignes
   - 02 - Boissons alcoolisées et tabac                           :    192 lignes
   - 03 - Articles d'habillement et chaussures                    :      7 lignes
   - 03 - Articles d'habillements et chaussures                   :    185 lignes
   - 04 - Logement, eau, électricité et autres combustibles       :      4 lignes
   - 04 - Logements, eau, électricité et autres combustibles      :    186 lignes
   - 04 - Logements, eau, électricité, gaz et autres combustibles :      2 lignes
   - 05 - Meubles, articles de ménage et entretien courant du foyer :      6 lignes
   - 05 - Meubles, articles de ménages et entretien courant du foyer :    162 lignes
   - 05 - Meubles,articles de ménages et entretien courant du foyer :     24 lignes
   - 06 - Santé                                                   :    164 lignes
   - 06 – Santé                                                   :     28 lignes
   - 07 - Transport                                               :    164 lignes
   - 07 – Transport                                               :     28 lignes
   - 08 - Communication                                           :    153 lignes
   - 08 - Communications                                          :     11 lignes
   - 08 – Communication                                           :     28 lignes
   - 09 - Loisirs et culture                                      :    192 lignes
   - 10 - Enseignement                                            :    164 lignes
   - 10 – Enseignement                                            :     28 lignes
   - 11 - Restaurants et hôtels                                   :    192 lignes
   - 12 - Biens et services divers                                :    192 lignes
   - Ensemble                                                     :    192 lignes
   - Produits alimentaires                                        :    192 lignes
   - Produits non alimentaires                                    :    192 lignes

Catégories uniques après normalisation :
   Nombre : 15
   - 01 - Produits alimentaires et boissons non alcoolisées       :    192 lignes
   - 02 - Boissons alcoolisées et tabac                           :    192 lignes
   - 03 - Articles d'habillements et chaussures                   :    192 lignes
   - 04 - Logements, eau, électricité et autres combustibles      :    192 lignes
   - 05 - Meubles, articles de ménages et entretien courant du foyer :    192 lignes
   - 06 - Santé                                                   :    192 lignes
   - 07 - Transport                                               :    192 lignes
   - 08 - Communication                                           :    192 lignes
   - 09 - Loisirs et culture                                      :    192 lignes
   - 10 - Enseignement                                            :    192 lignes
   - 11 - Restaurants et hôtels                                   :    192 lignes
   - 12 - Biens et services divers                                :    192 lignes
   - Ensemble                                                     :    192 lignes
   - Produits alimentaires                                        :    192 lignes
   - Produits non alimentaires                                    :    192 lignes

Normalisation terminée : 25 → 15 catégories

================================================================================
ÉTAPE 3 : NETTOYAGE DES DONNÉES
================================================================================

Doublons supprimés : 0
Valeurs manquantes supprimées : 0

Plage IPC : 58.30 → 159.40
Période : 2010 → 2025

Nettoyage terminé : 2,880 lignes restantes

================================================================================
ÉTAPE 4 : PIVOTAGE DES DONNÉES
================================================================================

Dimensions du tableau pivoté : 192 lignes × 15 colonnes

Colonnes (catégories) :
   - 01 - Produits alimentaires et boissons non alcoolisées
   - 02 - Boissons alcoolisées et tabac
   - 03 - Articles d'habillements et chaussures
   - 04 - Logements, eau, électricité et autres combustibles
   - 05 - Meubles, articles de ménages et entretien courant du foyer
   - 06 - Santé
   - 07 - Transport
   - 08 - Communication
   - 09 - Loisirs et culture
   - 10 - Enseignement
   - 11 - Restaurants et hôtels
   - 12 - Biens et services divers
   - Ensemble
   - Produits alimentaires
   - Produits non alimentaires

Aperçu des données pivotées :

Division par produits  01 - Produits alimentaires et boissons non alcoolisées  \
annee mois
2010  août                                                         113.9
      avril                                                        115.6
      décembre                                                     114.5
      février                                                      112.5
      janvier                                                      110.2
      juillet                                                      111.4
      juin                                                         112.8
      mai                                                          115.6
      mars                                                         116.5
      novembre                                                     117.1

Division par produits  02 - Boissons alcoolisées et tabac  \
annee mois
2010  août                                          108.3
      avril                                         108.3
      décembre                                      108.3
      février                                       108.3
      janvier                                       108.2
      juillet                                       108.3
      juin                                          108.3
      mai                                           108.3
      mars                                          108.3
      novembre                                      108.3

Division par produits  03 - Articles d'habillements et chaussures  \
annee mois
2010  août                                                  103.7
      avril                                                 104.2
      décembre                                              105.1
      février                                               104.5
      janvier                                               104.5
      juillet                                               103.5
      juin                                                  103.7
      mai                                                   104.0
      mars                                                  104.3
      novembre                                              104.9

Division par produits  04 - Logements, eau, électricité et autres combustibles  \
annee mois
2010  août                                                         104.4
      avril                                                        104.2
      décembre                                                     104.6
      février                                                      104.2
      janvier                                                      104.2
      juillet                                                      104.3
      juin                                                         104.3
      mai                                                          104.3
      mars                                                         104.2
      novembre                                                     104.6

Division par produits  05 - Meubles, articles de ménages et entretien courant du foyer  \
annee mois
2010  août                                                         106.2

<style>
T1 {
    display: inline-block;
    background: linear-gradient(90deg,#ffb457,#ff7043);
    color: #fff;
    padding: 10px 16px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: 900;
    font-family: "Segoe UI", Roboto, Arial, sans-serif;
    box-shadow: 0 4px 10px rgba(0,0,0,0.12);
    letter-spacing: 0.2px;
    border: 1px solid rgba(255,255,255,0.15);
}
</style>

<T1>4- Indices du commerce extérieur (ICE)</T1>

In [ ]:
"""
Script de consolidation des Indices du Commerce Exterieur (ICE) - Maroc
Periode couverte : 2010 - 2025
Format de sortie : CSV long  trimestre | division | type | ice

Sources :
  0. [EMBARQUE]  Donnees mensuelles 2010-2012 par groupement (valeurs MAD CVS-CJO)
                 -> aggregees en trimestres, ventilees et converties en ICE (base 100 = 2017)
  1. [FICHIER]   Indices du commerce extérieur, série trimestrielle 2013 - 2019.xlsx
  2. [FICHIER]   Indice du commerce extérieur (Exportation) 2019 - 1- Indice trimestriel .xlsx
  3. [FICHIERS]  ice_t*.csv  (trimestriels 2024-2025)

Note sur les donnees 2010-2012 :
  La source originale fournit le groupement "6/7- Produits finis d'equipement" sans
  distinguer agricole et industriel. Le script ventile ce groupement en deux via des
  ratios calcules sur les donnees ICE 2013-2019 :
    - Export : ratio agri/(agri+indus) = 50/50 (tres stable, std=0.007)
    - Import : ratio variable par trimestre (T1=53.7%, T2=52.8%, T3=53.7%, T4=50.4%)
  Les ICE 2010-2012 sont ensuite calcules en base 100=2017 via les valeurs
  mensuelles MAD du fichier Donnees_comext_CVS-CJO.
"""

#----------------------------------CONFIGURATION

FICHIERS = {
    "xlsx_2013_2019": "../data/interim/maroc/ICE/Indices du commerce extérieur, série trimestrielle 2013 - 2019.xlsx",
    "xlsx_2019_2025": "../data/interim/maroc/ICE/Indice du commerce extérieur (Exportation) 2019 - 1- Indice trimestriel .xlsx",
    "comext":         "../data/interim/maroc/ICE/Données comext CVS-CJO août 2024.xlsx",
    "csv_pattern":    "../data/interim/maroc/ICE/ice_t*.csv",
}

FICHIER_SORTIE = "..\\data\\interim\\maroc\\ICE\\ICE_Maroc_long.csv"

# =========================================================
# RATIOS DE VENTILATION agri / (agri + indus)
# Calcules sur les donnees ICE 2013-2019
#   - Export : ~50/50, quasi-constant (std=0.007) -> moyenne globale
#   - Import : variable -> moyenne par T1/T2/T3/T4
# Bases 2017 des sous-groupements (Millions MAD, moy. des 4 trimestres 2017) :
#   derivees des valeurs comext 6/7 fusionne * ratio
# =========================================================

RATIO_AGRI_EXP = 0.5000

RATIO_AGRI_IMP = {1: 0.5371, 2: 0.5280, 3: 0.5374, 4: 0.5041}

# Bases 2017 en Millions MAD pour la conversion -> ICE base 100=2017
BASE_2017 = {
    # (division, type) : valeur_moyenne_2017 en Millions MAD
    # Groupements presents dans le fichier comext (calcules automatiquement ci-dessous)
    # Ces valeurs sont la solution de repli si le fichier comext n'est pas disponible
    "6- Produits finis d'equipement agricole_export":    1890.0,
    "6- Produits finis d'equipement agricole_import":    4760.2,
    "7- Produits finis d'equipement industriel_export":  1890.0,
    "7- Produits finis d'equipement industriel_import":  4278.4,
}

# =========================================================
# DONNEES 2010-2012 EMBARQUEES
# Source : Donnees_comext_CVS-CJO - 3 feuilles
# Unite  : Millions MAD (groupements) | Milliards MAD (totaux)
# =========================================================

_TOTAL = """\
janv.-10\t11.5\t23.0
fevr.-10\t9.6\t20.7
mars-10\t11.1\t25.1
avr.-10\t11.1\t24.6
mai-10\t11.5\t23.4
juin-10\t13.2\t25.5
juil.-10\t12.5\t25.5
aout-10\t12.9\t23.7
sept.-10\t13.3\t25.2
oct.-10\t13.7\t25.5
nov.-10\t13.4\t24.9
dec.-10\t15.4\t28.3
janv.-11\t14.0\t28.5
fevr.-11\t14.8\t29.1
mars-11\t13.8\t29.7
avr.-11\t14.4\t30.8
mai-11\t14.0\t28.2
juin-11\t14.2\t28.8
juil.-11\t14.9\t28.1
aout-11\t15.4\t29.7
sept.-11\t14.5\t30.1
oct.-11\t14.1\t28.4
nov.-11\t14.9\t30.4
dec.-11\t15.3\t33.3
janv.-12\t15.6\t32.7
fevr.-12\t15.8\t34.5
mars-12\t15.8\t29.9
avr.-12\t14.4\t31.2
mai-12\t14.5\t35.4
juin-12\t15.0\t29.5
juil.-12\t15.2\t32.0
aout-12\t16.2\t31.5
sept.-12\t16.0\t30.0
oct.-12\t16.1\t35.8
nov.-12\t15.2\t33.4
dec.-12\t15.3\t31.4"""

_IMPORT_GU = """\
janv.-10\t2134.9\t5658.6\t708.9\t393.6\t4759.9\t5120.3\t4273.7
fevr.-10\t2042.1\t4491.1\t620.9\t312.6\t4667.9\t4258.4\t4293.0
mars-10\t2269.2\t6101.7\t804.8\t419.6\t4933.0\t5476.5\t5135.2
avr.-10\t1766.9\t5339.9\t1068.3\t405.5\t4726.9\t6994.3\t4257.6
mai-10\t2117.3\t4962.0\t646.3\t538.4\t5163.1\t5398.6\t4544.7
juin-10\t2665.0\t5901.4\t1144.5\t356.2\t5289.5\t5480.4\t4673.7
juil.-10\t2200.4\t5101.1\t1075.8\t393.3\t5340.5\t6831.9\t4566.8
aout-10\t2114.6\t5009.4\t1013.3\t423.3\t4977.8\t5342.7\t4769.5
sept.-10\t2908.4\t6512.4\t744.1\t414.0\t4986.0\t5121.7\t4492.3
oct.-10\t3143.8\t5870.5\t1136.4\t384.8\t5639.4\t4811.7\t4481.6
nov.-10\t2855.8\t5705.4\t734.1\t475.3\t5371.9\t5176.6\t4532.3
dec.-10\t2841.6\t7444.7\t1051.7\t588.0\t5672.4\t5595.7\t5094.5
janv.-11\t3404.2\t7222.5\t1227.5\t581.3\t5869.1\t5258.9\t4917.3
fevr.-11\t3513.0\t6995.5\t1238.1\t619.0\t6169.1\t5540.1\t5022.3
mars-11\t4372.1\t6890.3\t1051.0\t734.4\t6098.0\t5393.5\t5169.8
avr.-11\t3448.8\t8446.1\t1062.2\t674.8\t6398.0\t5659.1\t5076.2
mai-11\t2112.3\t7896.7\t1078.5\t734.1\t5998.2\t5529.5\t4899.1
juin-11\t3198.6\t7318.1\t860.1\t773.1\t6382.4\t5212.5\t5021.3
juil.-11\t3120.8\t6374.5\t1006.8\t1091.6\t6236.4\t5406.9\t4910.2
aout-11\t2480.7\t8229.0\t983.7\t876.2\t6248.5\t5911.9\t4953.3
sept.-11\t2343.3\t7721.9\t1429.2\t827.3\t6702.7\t5794.4\t5327.6
oct.-11\t2753.1\t6512.2\t817.7\t737.9\t6568.6\t5806.1\t5245.3
nov.-11\t3132.7\t7253.3\t1232.7\t807.2\t6494.2\t6100.8\t5371.0
dec.-11\t4477.4\t8818.7\t1110.0\t858.6\t6749.1\t6111.4\t5154.8
janv.-12\t3112.3\t8008.5\t1067.5\t971.2\t7145.6\t6236.3\t6147.3
fevr.-12\t3292.3\t11013.1\t1118.0\t1268.5\t6288.2\t6076.9\t5439.2
mars-12\t3079.0\t8424.4\t931.8\t499.2\t5621.1\t6113.1\t5238.5
avr.-12\t3290.1\t9323.4\t938.5\t686.7\t6205.6\t5448.6\t5352.4
mai-12\t3494.1\t10615.3\t1337.6\t841.4\t6949.2\t6283.7\t5840.7
juin-12\t3302.8\t5743.4\t1126.8\t1058.6\t6487.4\t6545.5\t5276.9
juil.-12\t3442.4\t8997.6\t1014.9\t789.9\t6250.1\t5943.4\t5565.4
aout-12\t3704.0\t7393.9\t951.6\t814.7\t6734.0\t6440.8\t5482.9
sept.-12\t2593.7\t7513.4\t1022.9\t809.0\t6447.8\t6405.2\t5173.8
oct.-12\t4785.2\t11106.9\t746.4\t971.2\t6384.6\t6415.2\t5427.9
nov.-12\t3821.5\t10221.4\t1227.8\t822.9\t6367.2\t5860.1\t5100.4
dec.-12\t3891.9\t8939.2\t1174.0\t805.4\t6107.9\t5315.2\t5119.5"""

_EXPORT_GU = """\
janv.-10\t2456.6\t80.8\t256.1\t988.5\t3564.9\t1407.6\t2709.5
fevr.-10\t1983.1\t54.5\t413.3\t815.5\t2100.2\t1466.8\t2765.3
mars-10\t1780.1\t105.9\t257.9\t965.1\t3287.8\t2061.4\t2635.3
avr.-10\t2240.1\t158.8\t287.5\t1050.1\t3084.2\t1448.0\t2798.3
mai-10\t2200.0\t142.0\t257.4\t1226.0\t3323.9\t1474.7\t2840.2
juin-10\t1982.2\t173.4\t298.1\t1238.7\t4252.6\t2299.9\t2926.0
juil.-10\t2180.9\t125.7\t347.8\t1162.2\t3466.4\t1961.3\t3219.3
aout-10\t2353.9\t124.8\t435.8\t1178.0\t3757.7\t2109.0\t2982.9
sept.-10\t2111.6\t137.7\t271.6\t1191.2\t3796.8\t2065.7\t3701.3
oct.-10\t2525.7\t136.1\t315.2\t1698.0\t3743.2\t2145.1\t3173.5
nov.-10\t2128.6\t151.4\t290.4\t1434.5\t4110.9\t1942.4\t3389.2
dec.-10\t2532.1\t197.7\t335.4\t1248.1\t4808.0\t2882.3\t3390.0
janv.-11\t2178.8\t435.5\t341.6\t1421.8\t4415.3\t2089.3\t3130.5
fevr.-11\t2615.3\t297.6\t295.2\t1636.2\t4703.7\t2003.7\t3208.3
mars-11\t2641.6\t288.9\t338.7\t1480.9\t3843.1\t2119.3\t3102.8
avr.-11\t2448.9\t198.6\t284.0\t1453.0\t4451.0\t2248.5\t3295.6
mai-11\t2210.3\t425.9\t348.2\t1524.9\t4413.9\t1841.7\t3224.4
juin-11\t2186.6\t342.4\t292.4\t1399.3\t4541.1\t2285.3\t3194.3
juil.-11\t2109.4\t366.5\t271.8\t1564.6\t4890.5\t2118.4\t3555.9
aout-11\t2089.1\t274.8\t273.2\t1515.1\t4511.4\t2886.7\t3848.2
sept.-11\t2313.2\t389.9\t231.4\t1899.2\t4582.1\t2161.9\t2969.4
oct.-11\t2264.2\t424.9\t256.0\t1854.1\t4668.6\t2071.1\t2566.4
nov.-11\t2544.5\t459.6\t215.2\t1577.9\t4488.2\t2473.9\t3127.0
dec.-11\t2473.1\t636.6\t178.6\t1842.5\t4411.7\t2394.8\t3379.2
janv.-12\t2441.3\t451.9\t210.3\t1766.5\t4364.3\t2988.7\t3378.3
fevr.-12\t2608.2\t613.3\t220.4\t1714.1\t4812.8\t2441.2\t3382.3
mars-12\t2186.2\t1307.4\t206.4\t1613.3\t4406.4\t2372.6\t3703.3
avr.-12\t2205.2\t452.5\t240.2\t1458.4\t4111.1\t2326.5\t3616.0
mai-12\t2566.9\t438.0\t244.6\t1382.5\t4211.8\t2138.6\t3534.6
juin-12\t2758.9\t298.6\t235.3\t1464.4\t4170.5\t2222.7\t3871.6
juil.-12\t2584.0\t439.1\t275.8\t2077.6\t4558.3\t1557.4\t3741.1
aout-12\t2853.8\t759.1\t286.0\t1661.9\t4292.5\t2255.7\t4116.4
sept.-12\t2525.5\t538.5\t340.0\t1413.3\t4746.8\t2348.7\t4053.8
oct.-12\t2453.1\t831.3\t384.0\t1474.0\t4704.7\t2236.1\t4063.4
nov.-12\t2543.6\t779.5\t296.1\t1503.4\t4243.6\t2277.5\t3517.9
dec.-12\t2465.9\t505.8\t321.1\t1459.7\t4164.0\t2231.8\t4128.9"""

# Colonnes des feuilles GU (ordre identique export et import)
_GU_COLS = [
    "1- Alimentation, boissons et tabacs",
    "2- Energie et lubrifiants",
    "3- Produits bruts d'origine animale et vegetale",
    "4- Produits bruts d'origine minerale",
    "5- Demi-Produits",
    "6/7- Produits finis d'equipement",   # sera ventile en 6 et 7
    "8- Produits finis de consommation",
]


#--------------------------------------NORMALISATION DES NOMS

DIV_MAP = {
    # xlsx 2013-2019
    "ALIMENTATION, BOISSONS ET TABACS":                 "1- Alimentation, boissons et tabacs",
    "ENERGIE  ET  LUBRIFIANTS":                         "2- Energie et lubrifiants",
    "PRODUITS BRUTS D'ORIGINE ANIMALE ET VEGETALE":     "3- Produits bruts d'origine animale et vegetale",
    "PRODUITS BRUTS D'ORIGINE MINERALE":                "4- Produits bruts d'origine minerale",
    "DEMI  PRODUITS":                                   "5- Demi-Produits",
    "PRODUITS FINIS D'EQUIPEMENT AGRICOLE":             "6- Produits finis d'equipement agricole",
    "PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL":           "7- Produits finis d'equipement industriel",
    "PRODUITS FINIS DE CONSOMMATION":                   "8- Produits finis de consommation",
    "EXPORTATIONS": "EXPORTATIONS",  "Exportation": "EXPORTATIONS",
    "IMPORTATIONS": "IMPORTATIONS",  "Importation": "IMPORTATIONS",
    # xlsx 2019-2025
    "Alimentation, boissons et tabacs":                 "1- Alimentation, boissons et tabacs",
    "Energie et  lubrifiants":                          "2- Energie et lubrifiants",
    "Produits bruts d'origine animale et vegetale":     "3- Produits bruts d'origine animale et vegetale",
    "Produits bruts d'origine minerale":                "4- Produits bruts d'origine minerale",
    "Demi  produits":                                   "5- Demi-Produits",
    "Produits finis d'equipement agricole":             "6- Produits finis d'equipement agricole",
    "Produits finis d'equipement industriel":           "7- Produits finis d'equipement industriel",
    "Produits finis de consommation":                   "8- Produits finis de consommation",
    # CSV 2024-2025
    "1- Alimentation, boissons et tabacs":              "1- Alimentation, boissons et tabacs",
    "2- Energie et lubrifiants":                        "2- Energie et lubrifiants",
    "3- Produits bruts d'origine animale et vegetale":  "3- Produits bruts d'origine animale et vegetale",
    "4- Produits bruts d'origine minerale":             "4- Produits bruts d'origine minerale",
    "5- Demi-Produits":                                 "5- Demi-Produits",
    "6- Produits finis d'equipement agricole":          "6- Produits finis d'equipement agricole",
    "7- Produits finis d'equipement industriel":        "7- Produits finis d'equipement industriel",
    "8- Produits finis de consommation":                "8- Produits finis de consommation",
    # comext (feuilles GU)
    "ALIMENTATION, BOISSON ET TABAC CVS-CJO":           "1- Alimentation, boissons et tabacs",
    "ENERGIE ET LUBRIFIANTS CVS-CJO":                   "2- Energie et lubrifiants",
    "PRODUITS BRUTS D'ORIGINE ANIMALE ET VEGETALE CVS-CJO": "3- Produits bruts d'origine animale et vegetale",
    "PRODUITS BRUTS D'ORIGINE MINERALE CVS-CJO":        "4- Produits bruts d'origine minerale",
    "DEMI PRODUITS CVS-CJO":                            "5- Demi-Produits",
    "PRODUITS FINIS D'EQUIPEMENT CVS-CJO":              "6/7- Produits finis d'equipement",
    "PRODUITS FINIS DE CONSOMMATION CVS-CJO":           "8- Produits finis de consommation",
}

MOIS_MAP = {
    "janv.": 1, "fevr.": 2, "mars": 3, "avr.": 4,
    "mai": 5, "juin": 6, "juil.": 7, "aout": 8,
    "sept.": 9, "oct.": 10, "nov.": 11, "dec.": 12,
}
TRIM_MAP = {1:"T1",2:"T1",3:"T1", 4:"T2",5:"T2",6:"T2",
            7:"T3",8:"T3",9:"T3", 10:"T4",11:"T4",12:"T4"}

def norm_div(d):
    return DIV_MAP.get(str(d).strip(), str(d).strip())

def norm_trimestre(t):
    t = str(t).strip()
    m = re.match(r"(\d{4})T(\d)", t)
    return f"T{m.group(2)}/{m.group(1)}" if m else t

def parse_date_fr(s):
    """'janv.-10' -> 'T1/2010'"""
    s = s.strip()
    dash = s.rfind("-")
    mois_str = s[:dash]
    annee = 2000 + int(s[dash + 1:])
    mois = MOIS_MAP[mois_str]
    return f"{TRIM_MAP[mois]}/{annee}"

def tri_sort_key(t):
    m = re.match(r"T(\d)/(\d{4})", t)
    return (int(m.group(2)), int(m.group(1))) if m else (9999, 9)


# =========================================================
# ETAPE 0A : Parser les donnees 2010-2012 -> trimestriel (somme)
# =========================================================

print("Etape 0 : traitement des donnees 2010-2012 embarquees...")

def parse_gu_block(raw, cols, typ):
    rows = []
    for line in raw.strip().split("\n"):
        parts = line.split("\t")
        tri = parse_date_fr(parts[0])
        for ci, col in enumerate(cols):
            rows.append({"trimestre": tri, "division": col,
                         "valeur": float(parts[ci + 1]), "type": typ})
    return pd.DataFrame(rows)

df_imp_gu = parse_gu_block(_IMPORT_GU, _GU_COLS, "import")
df_exp_gu = parse_gu_block(_EXPORT_GU, _GU_COLS, "export")

# Totaux : Milliards -> Millions MAD
rows_tot = []
for line in _TOTAL.strip().split("\n"):
    parts = line.split("\t")
    tri = parse_date_fr(parts[0])
    rows_tot.append({"trimestre": tri, "valeur": float(parts[1]) * 1000,
                     "type": "export", "division": "EXPORTATIONS"})
    rows_tot.append({"trimestre": tri, "valeur": float(parts[2]) * 1000,
                     "type": "import", "division": "IMPORTATIONS"})
df_tot_gu = pd.DataFrame(rows_tot)

# Agregation mensuelle -> trimestrielle (somme)
df_2010_q = (pd.concat([df_exp_gu, df_imp_gu, df_tot_gu], ignore_index=True)
               .groupby(["trimestre", "division", "type"])["valeur"]
               .sum().reset_index())


# =========================================================
# ETAPE 0B : Ventiler "6/7" en "6 agricole" + "7 industriel"
#   Export : ratio agri = 50.00% (stable)
#   Import : ratio agri variable par Tx (calcule sur 2013-2019)
# =========================================================

print("  Ventilation 6/7 -> 6 agricole + 7 industriel...")

rows_split = []
df_67 = df_2010_q[df_2010_q["division"] == "6/7- Produits finis d'equipement"].copy()

for _, row in df_67.iterrows():
    t_num = int(row["trimestre"][1])
    r_agri = RATIO_AGRI_EXP if row["type"] == "export" else RATIO_AGRI_IMP[t_num]
    r_indus = 1 - r_agri
    val = row["valeur"]
    rows_split.append({**row.to_dict(),
                        "division": "6- Produits finis d'equipement agricole",
                        "valeur": round(val * r_agri, 1)})
    rows_split.append({**row.to_dict(),
                        "division": "7- Produits finis d'equipement industriel",
                        "valeur": round(val * r_indus, 1)})

df_2010_q = pd.concat([
    df_2010_q[df_2010_q["division"] != "6/7- Produits finis d'equipement"],
    pd.DataFrame(rows_split)
], ignore_index=True)

print(f"  -> {len(df_2010_q)} lignes trimestrielles 2010-2012")


# =========================================================
# ETAPE 0C : Calculer les bases 2017 depuis le fichier comext
#            puis convertir les valeurs MAD -> ICE base 100=2017
# =========================================================

comext_path = FICHIERS["comext"]
base_map = {}

if os.path.exists(comext_path):
    print(f"  Lecture {comext_path} pour calcul des bases 2017...")

    def comext_sheet_to_tidy(sheet_name, typ):
        df_raw = pd.read_excel(comext_path, sheet_name=sheet_name, header=None)
        cols = [norm_div(str(c).strip()) for c in df_raw.iloc[0, 1:].tolist()]
        rows = []
        for ri in range(1, len(df_raw)):
            try:
                dt = pd.to_datetime(df_raw.iloc[ri, 0])
                tri = f"T{((dt.month-1)//3)+1}/{dt.year}"
            except:
                continue
            for ci, col in enumerate(cols):
                val = df_raw.iloc[ri, ci + 1]
                if pd.notna(val):
                    rows.append({"trimestre": tri, "division": col,
                                 "valeur": float(val), "type": typ})
        return pd.DataFrame(rows)

    df_gu_all = pd.concat([
        comext_sheet_to_tidy(" Import GU CVS-CJO", "import"),
        comext_sheet_to_tidy("Export GU CVS-CJO",  "export"),
    ], ignore_index=True)

    # Totaux
    df_tot_c = pd.read_excel(comext_path, sheet_name="TOTAL CVS-CJO", header=None)
    rows_tc = []
    for ri in range(1, len(df_tot_c)):
        try:
            dt = pd.to_datetime(df_tot_c.iloc[ri, 0])
            tri = f"T{((dt.month-1)//3)+1}/{dt.year}"
        except:
            continue
        rows_tc.append({"trimestre": tri, "division": "EXPORTATIONS",
                        "valeur": float(df_tot_c.iloc[ri, 1]) * 1000, "type": "export"})
        rows_tc.append({"trimestre": tri, "division": "IMPORTATIONS",
                        "valeur": float(df_tot_c.iloc[ri, 2]) * 1000, "type": "import"})
    df_gu_all = pd.concat([df_gu_all, pd.DataFrame(rows_tc)], ignore_index=True)

    # Moyenne 2017 par (division, type) -> valeur de reference ICE=100
    df_2017 = df_gu_all[df_gu_all["trimestre"].str.endswith("/2017")]
    df_base = df_2017.groupby(["division", "type"])["valeur"].mean().reset_index()
    base_map = {(r["division"], r["type"]): r["val_base"]
                for _, r in df_base.rename(columns={"valeur": "val_base"}).iterrows()}

    # Ajouter les bases agri/indus derivees du 6/7 fusionne
    base_67_exp = base_map.get(("6/7- Produits finis d'equipement", "export"), 3780.0)
    base_67_imp = base_map.get(("6/7- Produits finis d'equipement", "import"), 9038.6)
    ratio_agri_imp_mean = sum(RATIO_AGRI_IMP.values()) / len(RATIO_AGRI_IMP)

    base_map[("6- Produits finis d'equipement agricole",   "export")] = base_67_exp * RATIO_AGRI_EXP
    base_map[("7- Produits finis d'equipement industriel", "export")] = base_67_exp * (1 - RATIO_AGRI_EXP)
    base_map[("6- Produits finis d'equipement agricole",   "import")] = base_67_imp * ratio_agri_imp_mean
    base_map[("7- Produits finis d'equipement industriel", "import")] = base_67_imp * (1 - ratio_agri_imp_mean)

    print(f"  -> Bases 2017 calculees pour {len(base_map)} combinaisons (division, type)")
else:
    # Fallback : utiliser les valeurs precalculees embarquees
    print(f"  ATTENTION : {comext_path} introuvable -> utilisation des bases 2017 precalculees.")
    # Bases precalculees pour les groupements GU (en Millions MAD, moy. 2017)
    fallback_bases = {
        ("1- Alimentation, boissons et tabacs",                "export"): 2533.6,
        ("1- Alimentation, boissons et tabacs",                "import"): 3095.8,
        ("2- Energie et lubrifiants",                          "export"):  192.1,
        ("2- Energie et lubrifiants",                          "import"): 10434.5,
        ("3- Produits bruts d'origine animale et vegetale",    "export"):  433.8,
        ("3- Produits bruts d'origine animale et vegetale",    "import"):  2136.6,
        ("4- Produits bruts d'origine minerale",               "export"): 3998.1,
        ("4- Produits bruts d'origine minerale",               "import"):  641.5,
        ("5- Demi-Produits",                                   "export"): 4362.7,
        ("5- Demi-Produits",                                   "import"): 7456.3,
        ("6- Produits finis d'equipement agricole",            "export"): 1890.0,
        ("6- Produits finis d'equipement agricole",            "import"): 4760.2,
        ("7- Produits finis d'equipement industriel",          "export"): 1890.0,
        ("7- Produits finis d'equipement industriel",          "import"): 4278.4,
        ("8- Produits finis de consommation",                  "export"): 3297.5,
        ("8- Produits finis de consommation",                  "import"): 4161.1,
        ("EXPORTATIONS",                                       "export"): 16622.7,
        ("IMPORTATIONS",                                       "import"): 34543.9,
    }
    base_map = fallback_bases

# Conversion valeurs 2010-2012 -> ICE
records_2010_ice = []
no_base = []
for _, row in df_2010_q.iterrows():
    key = (row["division"], row["type"])
    base = base_map.get(key)
    if base and base > 0:
        ice_val = round(row["valeur"] / base * 100, 1)
    else:
        ice_val = round(row["valeur"], 1)
        no_base.append(key)
    records_2010_ice.append({
        "trimestre": row["trimestre"],
        "division":  row["division"],
        "ice":       ice_val,
        "type":      row["type"],
    })

if no_base:
    print(f"  ATTENTION : base 2017 manquante pour : {set(no_base)}")

df_2010_2012 = pd.DataFrame(records_2010_ice)
print(f"  -> {len(df_2010_2012)} lignes ICE 2010-2012 pret")


# =========================================================
# SOURCE 1 : xlsx 2013-2019
# =========================================================

print("Source 1 : 2013-2019...")
df_old = pd.read_excel(FICHIERS["xlsx_2013_2019"], header=None)
quarters = [str(c).strip() for c in df_old.iloc[0, 1:].tolist()]

r1 = []
for ri in range(1, 9):
    div = norm_div(df_old.iloc[ri, 0])
    for ci, q in enumerate(quarters):
        r1.append({"trimestre": q, "division": div, "ice": df_old.iloc[ri, ci+1], "type": "export"})
for ri in range(10, 18):
    div = norm_div(df_old.iloc[ri, 0])
    for ci, q in enumerate(quarters):
        r1.append({"trimestre": q, "division": div, "ice": df_old.iloc[ri, ci+1], "type": "import"})
for ci, q in enumerate(quarters):
    r1.append({"trimestre": q, "division": "EXPORTATIONS", "ice": df_old.iloc[18, ci+1], "type": "export"})
    r1.append({"trimestre": q, "division": "IMPORTATIONS", "ice": df_old.iloc[9,  ci+1], "type": "import"})

df_s1 = pd.DataFrame(r1)
print(f"  -> {len(df_s1)} lignes")


# =========================================================
# SOURCE 2 : xlsx 2019-2025 (export seulement)
# =========================================================

print("Source 2 : 2019-2025 (export)...")
df_xl2 = pd.read_excel(FICHIERS["xlsx_2019_2025"], header=None)
cols2  = [norm_div(c) for c in df_xl2.iloc[0, 1:].tolist()]

r2 = []
for ri in range(1, len(df_xl2)):
    q_raw = str(df_xl2.iloc[ri, 0]).strip()
    if not q_raw or q_raw == "nan": continue
    q = norm_trimestre(q_raw)
    for ci, div in enumerate(cols2):
        r2.append({"trimestre": q, "division": div, "ice": df_xl2.iloc[ri, ci+1], "type": "export"})

df_s2 = pd.DataFrame(r2)
print(f"  -> {len(df_s2)} lignes")


# =========================================================
# SOURCE 3 : CSV trimestriels 2024-2025
# =========================================================

print("Source 3 : CSV trimestriels...")
r3 = []
for f in sorted(glob.glob(FICHIERS["csv_pattern"])):
    df_csv = pd.read_csv(f, sep=None, engine="python")
    df_csv.columns = [c.strip().lstrip("\ufeff") for c in df_csv.columns]
    for _, row in df_csv.iterrows():
        q = f"T{str(row['trimestre']).replace('t','')}/{int(row['annee'])}"
        r3.append({"trimestre": q, "division": norm_div(row["division"]),
                   "ice": row["ice"], "type": row["type"]})

df_s3 = pd.DataFrame(r3)
print(f"  -> {len(df_s3)} lignes")


# =========================================================
# CONSOLIDATION (priorite : CSV > s2 > s1 > 2010-2012)
# =========================================================

print("\nConsolidation et deduplication...")
df_all = pd.concat([df_2010_2012, df_s1, df_s2, df_s3], ignore_index=True)

# Inverser pour que la plus haute priorite (CSV) soit en tete, puis keep='first'
df_all = (df_all.iloc[::-1]
          .drop_duplicates(subset=["trimestre", "division", "type"], keep="first")
          .iloc[::-1])

df_all["_key"] = df_all["trimestre"].map(tri_sort_key)
df_all = (df_all.sort_values(["_key", "type", "division"])
          .drop(columns="_key")
          .reset_index(drop=True))

print(f"Total lignes finales  : {len(df_all)}")
print(f"Trimestres couverts   : {df_all['trimestre'].min()} -> {df_all['trimestre'].max()}")
print(f"Trimestres distincts  : {df_all['trimestre'].nunique()}")


# =========================================================
# EXPORT
# =========================================================

df_all.to_csv(FICHIER_SORTIE, index=False, encoding="utf-8-sig")
print(f"\nFichier genere : {FICHIER_SORTIE}")

Etape 0 : traitement des donnees 2010-2012 embarquees...
  Ventilation 6/7 -> 6 agricole + 7 industriel...
  -> 216 lignes trimestrielles 2010-2012
  Lecture ../data/interim/maroc/ICE/Données comext CVS-CJO août 2024.xlsx pour calcul des bases 2017...
  -> Bases 2017 calculees pour 20 combinaisons (division, type)
  -> 216 lignes ICE 2010-2012 pret
Source 1 : 2013-2019...
  -> 486 lignes
Source 2 : 2019-2025 (export)...
  -> 207 lignes
Source 3 : CSV trimestriels...
  -> 125 lignes

Consolidation et deduplication...
Total lignes finales  : 1013
Trimestres couverts   : T1/2010 -> T4/2024
Trimestres distincts  : 62

Fichier genere : ..\data\interim\maroc\ICE\ICE_Maroc_long.csv

In [11]:
"""
Script de pivot final : ICE_Maroc_long.csv -> ICE_Maroc_pivot.csv

Structure de sortie :
  annee | trimestre | type | div1 | div2 | ... | TOTAL

  - 2 lignes par trimestre (une export, une import)
  - Chaque colonne = un groupement de produits
  - TOTAL = indice global (EXPORTATIONS ou IMPORTATIONS selon le type)
"""

FICHIER_ENTREE = "..\\data\\interim\\maroc\\ICE\\ICE_Maroc_long.csv"
FICHIER_SORTIE = "..\\data\\processed\\ICE_Maroc_pivot.csv"

# =========================================================
# NOMS CANONIQUES
# =========================================================

DIV_CANON = {
    "1- Alimentation, boissons et tabacs":               "1- Alimentation, boissons et tabacs",
    "2- Energie et lubrifiants":                         "2- Energie et lubrifiants",
    "ENERGIE  ET  LUBRIFIANTS":                          "2- Energie et lubrifiants",
    "Energie et  lubrifiants":                           "2- Energie et lubrifiants",
    "3- Produits bruts d'origine animale et vegetale":   "3- Prod. bruts animale et vegetale",
    "3- Produits bruts d'origine animale et végétale":   "3- Prod. bruts animale et vegetale",
    "Produits bruts d'origine animale et végétale":      "3- Prod. bruts animale et vegetale",
    "4- Produits bruts d'origine minerale":              "4- Prod. bruts minerale",
    "4- Produits bruts d'origine minérale":              "4- Prod. bruts minerale",
    "Produits bruts d'origine minérale":                 "4- Prod. bruts minerale",
    "5- Demi-Produits":                                  "5- Demi-Produits",
    "DEMI  PRODUITS":                                    "5- Demi-Produits",
    "Demi  produits":                                    "5- Demi-Produits",
    "6- Produits finis d'equipement agricole":           "6- Equipement agricole",
    "6- Produits finis d'équipement agricole":           "6- Equipement agricole",
    "Produits finis d'équipement agricole":              "6- Equipement agricole",
    "7- Produits finis d'equipement industriel":         "7- Equipement industriel",
    "7- Produits finis d'équipement industriel":         "7- Equipement industriel",
    "Produits finis d'équipement industriel":            "7- Equipement industriel",
    "8- Produits finis de consommation":                 "8- Prod. finis consommation",
    # EXPORTATIONS et IMPORTATIONS -> colonne TOTAL (chacun sur sa ligne type)
    "EXPORTATIONS":                                      "TOTAL",
    "IMPORTATIONS":                                      "TOTAL",
}

DIV_ORDER = [
    "1- Alimentation, boissons et tabacs",
    "2- Energie et lubrifiants",
    "3- Prod. bruts animale et vegetale",
    "4- Prod. bruts minerale",
    "5- Demi-Produits",
    "6- Equipement agricole",
    "7- Equipement industriel",
    "8- Prod. finis consommation",
    "TOTAL",
]

# =========================================================
# LECTURE ET NETTOYAGE
# =========================================================

print(f"Lecture de {FICHIER_ENTREE}...")
df = pd.read_csv(FICHIER_ENTREE, encoding="utf-8-sig")

# Normaliser apostrophes et espaces speciaux
df["division"] = df["division"].apply(
    lambda s: re.sub(r"[\xa0\u200b]+", " ",
                     str(s).replace("\u2019", "'").replace("\u2018", "'")).strip()
)

# Appliquer noms canoniques
df["division"] = df["division"].map(lambda x: DIV_CANON.get(x, x))

# Supprimer doublons
avant = len(df)
df = df.drop_duplicates(subset=["trimestre", "division", "type"], keep="first")
if avant != len(df):
    print(f"  {avant - len(df)} doublons supprimes")

# Decomposer 'T1/2020' -> annee=2020, trimestre='T1'
m = df["trimestre"].str.extract(r"T(\d)/(\d{4})")
df["annee"]     = m[1].astype(int)
df["trimestre"] = "T" + m[0]

print(f"  -> {len(df)} lignes propres")

# =========================================================
# PIVOT
# index  : annee + trimestre + type
# colonnes : divisions (chaque groupement devient une colonne)
# =========================================================

print("Pivot en cours...")

df_pivot = df.pivot_table(
    index=["annee", "trimestre", "type"],
    columns="division",
    values="ice",
    aggfunc="first",
).reset_index()
df_pivot.columns.name = None

# Ordonner les colonnes
cols = ["annee", "trimestre", "type"] + [d for d in DIV_ORDER if d in df_pivot.columns]
df_pivot = df_pivot[cols]

# Tri chronologique : annee -> trimestre -> export avant import
tri_order = {"T1": 1, "T2": 2, "T3": 3, "T4": 4}
df_pivot["_t"] = df_pivot["trimestre"].map(tri_order)
df_pivot = (df_pivot
            .sort_values(["annee", "_t", "type"])
            .drop(columns="_t")
            .reset_index(drop=True))

# =========================================================
# EXPORT
# =========================================================

df_pivot.to_csv(FICHIER_SORTIE, index=False, encoding="utf-8-sig")

print(f"\nFichier genere : {FICHIER_SORTIE}")
print(f"  Lignes   : {len(df_pivot)}  (2 par trimestre : export + import)")
print(f"  Colonnes : {len(df_pivot.columns)}  {list(df_pivot.columns)}")
print(f"\nApercu :")
print(df_pivot.head(8).to_string(index=False))

Lecture de ..\data\interim\maroc\ICE\ICE_Maroc_long.csv...
  42 doublons supprimes
  -> 971 lignes propres
Pivot en cours...

Fichier genere : ..\data\processed\ICE_Maroc_pivot.csv
  Lignes   : 108  (2 par trimestre : export + import)
  Colonnes : 12  ['annee', 'trimestre', 'type', '1- Alimentation, boissons et tabacs', '2- Energie et lubrifiants', '3- Prod. bruts animale et vegetale', '4- Prod. bruts minerale', '5- Demi-Produits', '6- Equipement agricole', '7- Equipement industriel', '8- Prod. finis consommation', 'TOTAL']

Apercu :
 annee trimestre   type  1- Alimentation, boissons et tabacs  2- Energie et lubrifiants  3- Prod. bruts animale et vegetale  4- Prod. bruts minerale  5- Demi-Produits  6- Equipement agricole  7- Equipement industriel  8- Prod. finis consommation  TOTAL
  2010        T1 export                                152.9                      125.6                               213.8                    219.7             205.1                   130.6                     130.6                        123.1  155.7
  2010        T1 import                                184.7                      280.9                               198.2                    174.9             182.0                   167.6                     160.7                        164.9  189.9
  2010        T2 export                                157.8                      247.0                               194.4                    278.9             244.2                   138.2                     138.2                        130.0  173.1
  2010        T2 import                                187.6                      280.0                               265.5                    202.0             192.4                   198.3                     197.2                        162.2  202.8
  2010        T3 export                                163.3                      202.2                               243.3                    280.2             252.5                   162.3                     162.3                        150.4  187.1
  2010        T3 import                                206.9                      287.3                               263.0                    191.2             193.9                   195.3                     187.0                        166.4  205.3
  2010        T4 export                                176.6                      252.7                               217.0                    347.6             290.1                   184.4                     184.4                        151.1  205.5
  2010        T4 import                                253.3                      328.7                               271.3                    225.0             211.4                   165.0                     180.6                        169.8  217.2